# Tested with golangci-lint ver. 2.x
version: "2"

run:
  timeout: 10m

linters:
  default: none
  enable:
    - asciicheck        # checks for non-ASCII identifiers
    - bidichk           # checks for dangerous unicode sequences (security)
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    # TODO fix issues- dupl
    - errcheck
    - errname           # checks error naming conventions
    - exhaustive
    # TODO fix issues- funlen
    - gocheckcompilerdirectives  # validates go compiler directives
    #- gochecknoinits
    - goconst
    # TODO fix issues- gocritic
    # TODO fix issues- gocyclo
    # gofmt and goimports are now formatters in v2, not linters
    # TODO fix issues- mnd (formerly gomnd)
    - goprintffuncname
    # TODO fix issues- gosec
    # gosimple and stylecheck are now part of staticcheck in v2
    - staticcheck
    #- govet
    - ineffassign
    # TODO fix issues- intrange (2 issues - use integer ranges Go 1.22+)
    # TODO fix issues- lll
    - makezero          # finds slice declarations with non-zero initial length
    - misspell
    - nakedret
    # TODO fix issues- nilerr (3 issues - returns nil when error is not nil)
    # TODO fix issues- noctx (4 issues - missing context.Context)
    # TODO fix issues- prealloc
    - reassign          # checks package variable reassignment
    - unconvert
    # TODO fix issues- unparam
    - unused
    - whitespace

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: "logging is allowed only by logutils.Log"
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - ifElseChain    # style preference - suggests switch over if-else
        - whyNoLint      # requires explanation for nolint directives
        - unnamedResult  # style preference - named return values
      settings:
        hugeParam:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 512
    gocyclo:
      min-complexity: 15
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
    lll:
      line-length: 140
    misspell:
      locale: US
    prealloc:
      # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
      # True by default.
      simple: true
      range-loops: true # Report preallocation suggestions on range loops, true by default
      for-loops: false # Report preallocation suggestions on for loops, false by default
    staticcheck:
      checks:
        - all
        - -QF1001  # De Morgan's law suggestions
        - -QF1003  # tagged switch suggestions
        - -QF1008  # embedded field selector suggestions
      dot-import-whitelist:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
        - github.com/onsi/gomega/gstruct

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - vendor/
      - .github/
      - manifests/
      - docs/
      - cluster/
      - hack/
      - automation/
      - examples/
    rules:
      # Exclude various linters from test files
      - path: _test\.go
        linters:
          - mnd
          - gosec
          - dupl
          - lll
          - goconst
      # Exclude linters from tests/ directory
      - path: ^tests/
        linters:
          - goconst

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/k8snetworkplumbingwg/ovs-cni