FROM quay.io/fedora/fedora:40-x86_64

RUN dnf -y install make git gcc openvswitch hostname && \
    dnf -y clean all

RUN mkdir -p /opt/cni/bin

ADD https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz /opt/cni/bin/

RUN cd /opt/cni/bin && \
    tar -xzf cni-plugins-linux-amd64-v1.0.1.tgz && \
    rm -f cni-plugins-linux-amd64-v1.0.1.tgz

ENV PATH="/opt/cni/bin:$PATH"

RUN printf '#!/bin/bash\nset -e\n/usr/share/openvswitch/scripts/ovs-ctl start --system-id=random\nexec "$@"\n' > /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
