name: "Push images on merge to main"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}-plugin
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
     
      - name: Prepare version file
        run: ./hack/get_version.sh > .version

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./cmd/Dockerfile
          labels: ${{ steps.docker_meta.outputs.labels }}
