name: Quality check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Install Go
        run: |
          make install-go
          echo "$(pwd)/build/_output/bin/go/bin" >> "$GITHUB_PATH"

      - name: Lint
        run: make lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Install Go
        run: |
          make install-go
          echo "$(pwd)/build/_output/bin/go/bin" >> "$GITHUB_PATH"

      - name: Build
        run: make build

  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Install Open vSwitch
        run: |
          sudo apt-get update
          sudo apt-get install -y openvswitch-switch

      - name: Start Open vSwitch services
        run: sudo /usr/share/openvswitch/scripts/ovs-ctl start --system-id=random

      - name: Install Go
        run: |
          make install-go
          echo "$(pwd)/build/_output/bin/go/bin" >> "$GITHUB_PATH"

      - name: Run unit tests
        run: sudo -E make test

  e2e:
    runs-on: ubuntu-latest
    needs: [lint, build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Install Go
        run: |
          make install-go
          echo "$(pwd)/build/_output/bin/go/bin" >> "$GITHUB_PATH"

      - name: Load openvswitch kernel module
        run: sudo modprobe openvswitch

      - name: Create Kind cluster with OVS and Multus
        run: make cluster-up

      - name: Build and deploy ovs-cni to the cluster
        run: make cluster-sync

      - name: Run functional tests
        run: make E2E_TEST_ARGS="-ginkgo.v -test.v -test.timeout 20m -ginkgo.noColor --ginkgo.junit-report=/tmp/junit-functest.xml" functest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: functest-results
          path: /tmp/junit-functest.xml
          if-no-files-found: ignore

      - name: Tear down Kind cluster
        if: always()
        run: make cluster-down
