name: lint-build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Install Go
        run: |
          make build/_output/bin/go/bin/go
          echo "$(pwd)/build/_output/bin/go/bin" >> "$GITHUB_PATH"

      - name: Lint
        run: make lint

      - name: Build
        run: make build
